language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - COMPOSER_FLAGS='update --prefer-lowest --prefer-stable'
  - COMPOSER_FLAGS='update'

install:
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script: vendor/phpunit/phpunit/phpunit --verbose tests/